// ignore_for_file: comment_references, implementation_imports

import 'package:ice/src/domain/domain.dart';
import 'package:ice_annotation/src/ice.dart';

/// {@template unions}
/// All classes that are annotated with [Ice]
/// {@endtemplate}
class IceSubjects {
  /// {@macro unions}
  IceSubjects() {
    _supertypes = {};
    _classes = {};
  }

  /// mapped by supertypes, contains a list of classes
  late final Map<String, List<Class>> _supertypes;

  /// mapped by class name, contains a class
  late final Map<String, Class> _classes;

  /// gets the classes assotiated with the union [base]
  List<Class> getUnions(String base) => _supertypes[base] ?? [];

  /// checks if the [subject] has been generated by ice
  bool hasGenerated(Class subject) => _classes.containsKey(subject.name);

  /// adds the [subject] to the list of [Ice] classes
  /// mapped by supertypes
  void add(Class subject) {
    _classes[subject.name] = subject;

    final subjectMap = subject.supertypeMap();

    for (final entry in subjectMap.entries) {
      if (!_supertypes.containsKey(entry.key)) {
        _supertypes[entry.key] = [];
      }

      _supertypes[entry.key]!.add(entry.value);
    }
  }
}
